python train_model.py -dataset activemq
python train_model.py -dataset camel
python train_model.py -dataset derby
python train_model.py -dataset groovy
python train_model.py -dataset hbase
python train_model.py -dataset hive
python train_model.py -dataset jruby
python train_model.py -dataset lucene
python train_model.py -dataset wicket